### ISSUE TITLE
Streaming operation?

### ISSUE THREAD

**Issue by kornelski** [magiclen/html-minifier#4]
I would like to process HTML with minimal buffering. `.digest()` is clever enough to operate on fragments, but accumulates the result instead of returning it.

Could you make it use `io::Write` instead of an internal buffer?

**Comment by magiclen** [comment]
Good idea. Let me see how to get rid of the private `remove` method first.

**Comment by magiclen** [comment]
The `HTMLMinifierHelper` struct with a low-level API has been added since `2.1.0`. The `digest` method of a `HTMLMinifierHelper` instance can pass an instance which implements the `io::Write` trait as an output destination.

And after `3.0.0`, this crate doesn't try to make HTML inline anymore in order to support `[u8]` input.
